# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160707_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='initials',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='account',
            name='khsid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
