# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160726_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
