# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20160727_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('outline_name', models.CharField(max_length=256)),
                ('speaker_full_name', models.CharField(max_length=256)),
                ('congregation_name', models.CharField(max_length=128)),
            ],
        ),
    ]
