# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_incoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField(default=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Account')),
            ],
        ),
    ]
